### ISSUE TITLE
figure suggestion

### ISSUE THREAD

**Issue by Jason-Conner-NOAA** [BenWilliams-NOAA/swo-tech#13]
For Figs 5-8, do we want to consider changing the base case to an outlined violin plot around the boxplots of all of the experimental cases? I have found this graphic to be useful for interpretation of comparing cases:
[unnamed-chunk-12-1.pdf](https://github.com/BenWilliams-NOAA/swo-tech/files/8979055/unnamed-chunk-12-1.pdf)

Also for horizontal bar plots (fig 9-10) a vline for the base case may also be more readable.

I'd be happy to work on the code.

**Comment by pete-hulson** [comment]
Let's check out what it'd look like - I'll be sending the draft out to the group here in a bit, but let's work on this over the next week or so. We should have all the figure code and output up in the repo by next week

**Comment by Jason-Conner-NOAA** [comment]
Done.
